# Intro

As CARAMA employs a stochastic algorithm, its results vary slightly with each iteration.

To identify outliers, I have set the number of iterations to 1, which should be sufficient when utilizing CARMA for outlier detection.

For comparison with the R version (see script 01_R_Run.R), I have established the following concordance criteria:

1. The correlation between PIPs greater than 0.8.
2. The ratio between the length of the intersection of the list of outliers and the length of outliers for both versions should exceed 0.6.

To increase the concordance fo outliers we need to increase the BF threshold but I want to leave these test with defaul parameters. 

The first and second tests have one outlier that I induced artificially. The third one is more realistic example where number of outliers can vary depedning on the run of the CARMA.

In [11]:
import os
import numpy as np
import pandas as pd

In [12]:
os.chdir("../src/")

In [13]:
import carma_light as cl

# TEST 1

In [14]:
ld=pd.read_csv("../tests/01_test_ld.csv",header=None)
ld=np.array(ld)
z=pd.read_csv("../tests/01_test_z.csv")
z=np.array(z.iloc[:,1])

Rout=pd.read_csv("../tests/test1_o.csv")
Rout=Rout["Index"]-1
Rout=Rout.tolist()

Rpip=pd.read_csv("../tests/test1_pip.csv")
Rpip=Rpip["PIP"].tolist()

In [16]:
L1=cl.CARMA_spike_slab_noEM(z,ld,all_iter=1,outlier_switch=True)

ordering pizza...
N SNPs is 21


/Users/yt4/Projects/carmapy_light/src/carma_light.py:339: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:339: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

Zero step is finished in 0.74 sec
Expecting to finish in 0.74 sec


/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

pizza ordered!
FM time is 1.33 sec


/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

In [18]:
print("Corr between pips:")
print(np.corrcoef(L1["PIPs"],Rpip))
print("Intersection between outliers intersect->R:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(Rout))
print("Intersection between outliers intersect->Py:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(L1["Outliers"]))

Corr between pips:
[[1.         0.99943087]
 [0.99943087 1.        ]]
Intersection between outliers intersect->R:
1.0
Intersection between outliers intersect->Py:
1.0


# TEST 2

In [19]:
ld=np.load("../tests/02_test_ld.npy")
ld=np.array(ld)
z=pd.read_csv("../tests/02_test_z.csv")
z=np.array(z.iloc[:,1])

Rout=pd.read_csv("../tests/test2_o.csv")
Rout=Rout["Index"]-1
Rout=Rout.tolist()

Rpip=pd.read_csv("../tests/test2_pip.csv")
Rpip=Rpip["PIP"].tolist()

In [20]:
L1=cl.CARMA_spike_slab_noEM(z,ld,all_iter=1,outlier_switch=True)

ordering pizza...
N SNPs is 3390


/Users/yt4/Projects/carmapy_light/src/carma_light.py:339: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:339: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

Zero step is finished in 28.67 sec
Expecting to finish in 28.67 sec


/Users/yt4/Projects/carmapy_light/src/carma_light.py:339: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:339: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

pizza ordered!
FM time is 60.37 sec


In [21]:
print("Corr between pips:")
print(np.corrcoef(L1["PIPs"],Rpip))
print("Intersection between outliers intersect->R:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(Rout))
print("Intersection between outliers intersect->Py:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(L1["Outliers"]))

Corr between pips:
[[1.         0.99903591]
 [0.99903591 1.        ]]
Intersection between outliers intersect->R:
1.0
Intersection between outliers intersect->Py:
1.0


# TEST 3

In [22]:
ld=pd.read_csv("../tests/03_test_ld.csv",header=None)
ld=np.array(ld)
z=pd.read_csv("../tests/03_test_z.csv")
z=np.array(z.iloc[:,1])

Rout=pd.read_csv("../tests/test3_o.csv")
Rout=Rout["Index"]-1
Rout=Rout.tolist()

Rpip=pd.read_csv("../tests/test3_pip.csv")
Rpip=Rpip["PIP"].tolist()

In [23]:
L1=cl.CARMA_spike_slab_noEM(z,ld,all_iter=1,outlier_switch=True)

ordering pizza...
N SNPs is 621


/Users/yt4/Projects/carmapy_light/src/carma_light.py:339: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:339: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

Zero step is finished in 7.85 sec
Expecting to finish in 7.85 sec


/Users/yt4/Projects/carmapy_light/src/carma_light.py:339: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  add_B = pd.concat([add_B, new_row], ignore_index=True)
/Users/yt4/Projects/carmapy_light/src/carma_light.py:335: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this

pizza ordered!
FM time is 12.36 sec


In [24]:
print("Corr between pips:")
print(np.corrcoef(L1["PIPs"],Rpip))
print("Intersection between outliers intersect->R:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(Rout))
print("Intersection between outliers intersect->Py:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(L1["Outliers"]))

Corr between pips:
[[1.         0.98498961]
 [0.98498961 1.        ]]
Intersection between outliers intersect->R:
0.8
Intersection between outliers intersect->Py:
0.9090909090909091
