# Intro

As CARAMA employs a stochastic algorithm, its results vary slightly with each iteration.

To identify outliers, I have set the number of iterations to 1, which should be sufficient when utilizing CARMA for outlier detection.

For comparison with the R version (see script 01_R_Run.R), I have established the following concordance criteria:

1. The correlation between PIPs greater than 0.8.
2. The ratio between the length of the intersection of the list of outliers and the length of outliers for both versions should exceed 0.6.

To increase the concordance fo outliers we need to increase the BF threshold but I want to leave these test with defaul parameters. 

The first and second tests have one outlier that I induced artificially. The third one is more realistic example where number of outliers can vary depedning on the run of the CARMA.

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
os.chdir("../src/")

In [3]:
import carma_light as cl

# TEST 1

In [4]:
ld=pd.read_csv("../tests/01_test_ld.csv",header=None)
ld=np.array(ld)
z=pd.read_csv("../tests/01_test_z.csv")
z=np.array(z.iloc[:,1])

Rout=pd.read_csv("../tests/test1_o.csv")
Rout=Rout["Index"]-1
Rout=Rout.tolist()

Rpip=pd.read_csv("../tests/test1_pip.csv")
Rpip=Rpip["PIP"].tolist()

In [5]:
L1=cl.CARMA_spike_slab_noEM(z,ld,all_iter=1,outlier_switch=True)

ordering pizza...
N SNPs is 21
Zero step is finished in 1.09 sec
Expecting to finish in 1.09 sec
pizza ordered!
FM time is 2.38 sec


In [6]:
print("Corr between pips:")
print(np.corrcoef(L1["PIPs"],Rpip))
print("Intersection between outliers intersect->R:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(Rout))
print("Intersection between outliers intersect->Py:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(L1["Outliers"]))

Corr between pips:
[[1.         0.99900171]
 [0.99900171 1.        ]]
Intersection between outliers intersect->R:
1.0
Intersection between outliers intersect->Py:
1.0


# TEST 2

In [7]:
ld=np.load("../tests/02_test_ld.npy")
ld=np.array(ld)
z=pd.read_csv("../tests/02_test_z.csv")
z=np.array(z.iloc[:,1])

Rout=pd.read_csv("../tests/test2_o.csv")
Rout=Rout["Index"]-1
Rout=Rout.tolist()

Rpip=pd.read_csv("../tests/test2_pip.csv")
Rpip=Rpip["PIP"].tolist()

In [8]:
L1=cl.CARMA_spike_slab_noEM(z,ld,all_iter=1,outlier_switch=True)

ordering pizza...
N SNPs is 3390
Zero step is finished in 40.24 sec
Expecting to finish in 40.24 sec
pizza ordered!
FM time is 80.05 sec


In [9]:
print("Corr between pips:")
print(np.corrcoef(L1["PIPs"],Rpip))
print("Intersection between outliers intersect->R:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(Rout))
print("Intersection between outliers intersect->Py:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(L1["Outliers"]))

Corr between pips:
[[1.         0.99876797]
 [0.99876797 1.        ]]
Intersection between outliers intersect->R:
1.0
Intersection between outliers intersect->Py:
1.0


# TEST 3

In [10]:
ld=pd.read_csv("../tests/03_test_ld.csv",header=None)
ld=np.array(ld)
z=pd.read_csv("../tests/03_test_z.csv")
z=np.array(z.iloc[:,1])

Rout=pd.read_csv("../tests/test3_o.csv")
Rout=Rout["Index"]-1
Rout=Rout.tolist()

Rpip=pd.read_csv("../tests/test3_pip.csv")
Rpip=Rpip["PIP"].tolist()

In [11]:
L1=cl.CARMA_spike_slab_noEM(z,ld,all_iter=1,outlier_switch=True)

ordering pizza...
N SNPs is 621
Zero step is finished in 10.68 sec
Expecting to finish in 10.68 sec
pizza ordered!
FM time is 24.79 sec


In [12]:
print("Corr between pips:")
print(np.corrcoef(L1["PIPs"],Rpip))
print("Intersection between outliers intersect->R:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(Rout))
print("Intersection between outliers intersect->Py:")
print(len(set(Rout).intersection(L1["Outliers"]))/len(L1["Outliers"]))

Corr between pips:
[[1.        0.9998775]
 [0.9998775 1.       ]]
Intersection between outliers intersect->R:
0.64
Intersection between outliers intersect->Py:
0.8
